config/routes.rb
Rails.application.routes.draw do
  resources :recipes

  
  match '/auth/:provider/callback', :to => 'sessions#create', :via => [:get, :post]
  match 'auth/failure', :to => 'sessions#failure', :via => [:get, :post]
  match 'sessions/destroy', :as => 'logout', :via => [:get, :post]
  get 'sessions/clear'
  get 'sessions/debug'
  
  resources :users, only: [:destroy] do
    resources :profiles, only: [:show, :edit, :update, :destroy]
  end
  
  get 'welcome/landing', :as => :landing_page
  root 'welcome#landing'

  

 
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
	validates_presence_of :recipe_name
	validates_presence_of :ingredients
	validates_presence_of :calories
	validates_presence_of :food_type
	validates_presence_of :cooking_time
	
	def self.all_foods
    %w(Chicken Beef Pork Dessert Vegetarian)
  end

  def self.filter_and_sort(selected_foods, sorting)
    Recipe.where(food_type:selected_foods).order(sorting)
  end
  
  def self.similar_recipes ingredients1, ingredients2

    # This function defines the cosine similarity between two lists of ingredients
    # Example input: similar_recipes "Chicken Breast, Salt" "Chicken Breast, Oil"Example
    # Example output: 0.5 
    # The higher the cosine similarity, the more closely two lists of ingredients are related

    tf_vector1 = Array.new()
    tf_vector2 = Array.new()
    s1_token = ingredients1.downcase.split(',')#.downcase!.try(:split,",")#.to_set#.split(',').to_set
    s2_token = ingredients2.downcase.split(',')#.downcase!.try(:split,",")#.to_set#.split(',').to_set
    combined_vect = s1_token | s2_token
    
    for word in combined_vect do
      if s1_token.include? word
        tf_vector1.append(1)
      else
        tf_vector1.append(0)
      end
      if s2_token.include? word
        tf_vector2.append(1)
      else
        tf_vector2.append(0)
      end
    end
    
    c = 0
    combined_vect.each_with_index do |value, index|
      c += tf_vector1[index] * tf_vector2[index]  
    end
        
    cosine = c / ((tf_vector1.sum * tf_vector2.sum)**0.5).to_f
    return cosine
  end    
  
  def self.find_closest_recipe recipe
    
    #This function finds the closest recipe in terms of ingredients to the current one
    #It iterates through our list of recipes and uses similar_recipes() to find the closest match

    list_recipes = Recipe.all #need to define all_recipes function that gets list of all recipes
    sim = 0
    highest = recipe
    for r in list_recipes do
      if similar_recipes(recipe.ingredients, r.ingredients) > sim and recipe != r and recipe.food_type == r.food_type
        sim = similar_recipes(recipe.ingredients, r.ingredients)
        highest = r
      end
    end
    return highest
  end
end

app/controllers/recipes_controller.rb
require 'set'
class RecipesController < ApplicationController
   
  def show
    #id = params[:id] 
    #@recipe = Recipe.find(id) 
    # will render app/views/movies/show.<extension> by default
    @recipe = set_recipe
    @close_recipe = Recipe.find_closest_recipe(@recipe)
  end

  def index

    update_session_hash
    render_redirect
    #determine_highlighting
    
    #@recipes = cccc
    @all_foods = Recipe.all_foods
    @selected_foods_hash = session[:foods] #params[:ratings] || select_all_hash
    @selected_foods = selected_foods
    @sorting = session[:sorting] #params[:sorting] || "id"
    @recipes = Recipe.filter_and_sort(@selected_foods,@sorting)

  end

  def new
    # default: render 'new' template
  end

  def create
    @recipe = Recipe.create!(recipe_params)
    flash[:notice] = "#{@recipe.recipe_name} was successfully created."
    redirect_to recipes_path
  end

  def edit
    @recipe = set_recipe 
  end

  def update
    @recipe = set_recipe
    @recipe.update_attributes!(recipe_params)
    flash[:notice] = "#{@recipe.recipe_name} was successfully updated."
    redirect_to recipe_path(@recipe)
  end

  def destroy
    @recipe = set_recipe
    @recipe.destroy
    flash[:notice] = "Recipe '#{@recipe.recipe_name}' deleted."
    redirect_to recipes_path
  end
	
	
  private
  # Making "internal" methods private is not required, but is a common practice.
  # This helps make clear which methods respond to requests, and which ones do not.
  def recipe_params
    params.require(:recipe).permit(:recipe_name, :ingredients, :calories, :food_type, :cooking_time)
  end

  def selected_foods
    @selected_foods_hash.keys
  end
  
  def select_all_hash
    Hash[ Recipe.all_foods.map { |food_type| [ food_type , "1" ] } ]
  end
  
  def update_session_hash
    session[:foods] = params[:foods] || session[:foods] || select_all_hash
    session[:sorting] = params[:sorting] || session[:sorting] || "id"
  end
  
  def render_redirect
    return unless (session[:foods] and params[:foods].nil? ) or
                  (session[:sorting] and params[:sorting].nil? )
    redirect_to recipes_path(:sorting => session[:sorting] , :foods => session[:foods]) and return 
  end
  
	def set_recipe
		@recipe = Recipe.find params[:id]
	end
end

app/helpers/recipe_helper.rb
module RecipeHelper
end

app/views/recipes/edit.html.haml
%body.background_color
  %h2 Edit Recipe
  = form_tag recipe_path(@recipe), :method => :put do
    = label :recipe, :recipe_name, 'Name', :class => 'col-form-label'
    = text_field :recipe, :recipe_name, :class => 'form-control'
    = label :recipe, :ingredients, 'Ingredients', :class => 'col-form-label'
    = text_field :recipe, :ingredients, :class => 'form-control'
    = label :recipe, :calories, 'Calories', :class => 'col-form-label'
    = number_field :recipe, :calories, :class => 'form-control'
    = label :recipe, :food_type, 'Food Type', :class => 'col-form-label'
    = select :recipe, :food_type, ['Chicken','Beef', 'Pork','Dessert','Vegetarian'], {}, {:class => 'form-control col-1'}
    = label :recipe, :cooking_time, 'Cooking Time', :class => 'col-form-label'
    = number_field :recipe, :cooking_time, :class => 'form-control'
    %br/
    = submit_tag 'Update Recipe Info', :class => 'btn btn-primary'
    = link_to 'Cancel', recipes_path, :class => 'btn btn-secondary givemargin'

app/views/recipes/index.html.haml
%body.background_color
  %h2 All Recipes

  = form_tag recipes_path, method: :get, id: 'foods_form' do
    = hidden_field_tag "sorting", @sorting
    Include:
    - @all_foods.each do |food|
      .form-check.form-check-inline
        = label_tag "foods[#{food}]", food, class: 'form-check-label'
        = check_box_tag "foods[#{food}]", "1",  @selected_foods.include?(food), class: 'form-check-input', :id=> "foods_#{food}"
    = submit_tag 'Refresh', id: 'foods_submit', class: 'btn btn-primary'

  %table#recipes.table.table-striped.col-md-12
    %thead
      %tr
        %th 
          =link_to "Recipe Name", recipes_path(sorting: :recipe_name, :foods=>@selected_foods_hash),id: :recipes_header, class: 'linkto_color'
        %th Ingredients
        %th 
          =link_to "Food_Type", recipes_path(sorting: :food_type, :foods=>@selected_foods_hash),id: :food_type_header, class: 'linkto_color'
        %th 
          =link_to "Calories", recipes_path(sorting: :calories, :foods=>@selected_foods_hash),id: :calories_header, class: 'linkto_color'
        %th 
          =link_to "Cooking Time", recipes_path(sorting: :cooking_time, :foods=>@selected_foods_hash),id: :cooking_time_header, class: 'linkto_color'
    %tbody
      - @recipes.each do |recipe|
        %tr
          %td
            = link_to "#{recipe.recipe_name}", recipe_path(recipe), class: 'linkto_color'
          %td
            = recipe.ingredients
          %td
            = recipe.food_type
          %td
            = recipe.calories
          %td
            = recipe.cooking_time

  = link_to 'Add new recipe', new_recipe_path, :class => 'btn btn-primary givedownmargin'

app/views/recipes/main.html.haml
%body.background_image.tomiddle
  %h1.title RECIPE RECOMMENDER

  %br
    %filtering_field
      =text_field_tag 'Recipe Name', nil ,placeholder: 'Recipe Name', :class => 'form-control col-lg-2 tomiddle offset-5 giveupdownmargin'
      =text_field_tag 'Ingredients', nil ,placeholder: 'Ingredients', :class => 'form-control col-lg-2 tomiddle offset-5 giveupdownmargin'
      =text_field_tag 'Cuisine Type', nil ,placeholder: 'Cuisine Type', :class => 'form-control col-lg-2 tomiddle offset-5 giveupdownmargin'
      =text_field_tag 'Calories', nil ,placeholder: 'Calories', :class => 'form-control col-lg-2 tomiddle offset-5 giveupdownmargin'
      =text_field_tag 'Cooking Time(min)', nil ,placeholder: 'Cooking Time(min)', :class => 'form-control col-lg-2 tomiddle offset-5 giveupdownmargin'
      
      = submit_tag 'APPLY', :class => 'givedownmargin'

      

app/views/recipes/new.html.haml
%h2 Create New Recipe
= form_tag recipes_path, :class => 'form' do
  = label :recipe, :recipe_name, 'Name', :class => 'col-form-label'
  = text_field :recipe, :recipe_name, :class => 'form-control'
  = label :recipe, :ingredients, 'Ingredients', :class => 'col-form-label'
  = text_field :recipe, :ingredients, :class => 'form-control'
  = label :recipe, :calories, 'Calories', :class => 'col-form-label'
  = number_field :recipe, :calories, :class => 'form-control'
  = label :recipe, :cuisine_type, 'Cuisine Type', :class => 'col-form-label'
  = select :recipe, :cuisine_type, ['Japanese','Chinese', 'Thai'], {}, {:class => 'form-control col-1'}
  = label :recipe, :cooking_time, 'Cooking Time', :class => 'col-form-label'
  = number_field :recipe, :cooking_time, :class => 'form-control'
  %br/
  = submit_tag 'Save Changes', :class => 'btn btn-primary givedownmargin'
  = link_to 'Cancel', recipes_path, :class => 'btn btn-secondary givemargin givedownmargin'

app/views/recipes/show.html.haml
%body.background_color
  %h1
    %em= @recipe.recipe_name
  %ul#details
    %li
      Food Type:
      = @recipe.food_type
    %li
      Ingredients:
      = @recipe.ingredients
    %li
      Calories:
      = @recipe.calories
    %li
      Cooking Time:
      = @recipe.cooking_time
    %li
      Recipe that has similar ingredients:
      = link_to @close_recipe.recipe_name , recipe_path(@close_recipe),class: 'linkto_color'

  .row
    = link_to 'Edit', edit_recipe_path(@recipe), :class => 'btn btn-primary col-2 givemargin givedownmargin'
    = link_to 'Delete', recipe_path(@recipe), 'data-method' => 'delete', 'data-confirm' => 'Are you sure?', :class => 'btn btn-danger col-2 givedownmargin'
    = link_to 'Back to recipes list', recipes_path, :class => 'btn btn-primary col-2 givemargin givedownmargin'